site_name: OpenMiner

nav:
    - 'Home': 'index.md'
    - 'C++ classes in Lua': 'lua-api-cpp.md'
    - 'Lua: Core API':
        - 'openminer': 'lua-api-core.md'
    - 'Lua: Mod API':
        - 'Overview': 'lua-api-mod.md'
        - 'Biome': 'lua-api-biome.md'
        - 'Block': 'lua-api-block.md'
        - 'Dimension': 'lua-api-dimension.md'
        - 'Entity': 'lua-api-entity.md'
        - 'Item': 'lua-api-item.md'
        - 'Key': 'lua-api-key.md'
        - 'Recipe': 'lua-api-recipe.md'
        - 'Sky': 'lua-api-sky.md'
        - 'Tree': 'lua-api-tree.md'
    - 'Lua: GUI API':
        - 'Overview': 'lua-api-gui.md'
        - 'Crafting widget': 'lua-api-gui-crafting.md'
        - 'Image': 'lua-api-gui-image.md'
        - 'Inventory data': 'lua-api-gui-inventory-data.md'
        - 'Inventory widget': 'lua-api-gui-inventory.md'
        - 'Progress bar': 'lua-api-gui-progress-bar.md'
        - 'Scroll bar': 'lua-api-gui-scroll-bar.md'
        - 'Text input': 'lua-api-gui-text-input.md'
    - 'Misc':
      - 'Network Protocol': 'network-protocol.md'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - lua

extra_javascript:
  - script.js

